var mixed = ["hello", 10, 90, 5];
var mixTuple = [];
mixTuple[0] = 120;
mixTuple[1] = "Rajat";
console.log(mixTuple[0]);
mixTuple[3] = "hi";
console.log(mixTuple.length);
var mixNums = [10, "hello"];
var x = mixNums[0], y = mixNums[1];
var x = mixNums[0], y = mixNums[1], z = mixNums[2];
var p = mixNums[0];
console.log(x);
console.log(y);
console.log(z);
console.log(p);
